name: web_2
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.4
  websafe_svg: ^3.0.1+1
  equatable: ^2.0.5
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  get: ^4.6.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.2.0
  connectivity: ^3.0.6
  share: ^2.0.4
  flutter_cached_pdfview: ^0.4.2
  super_context_menu: ^0.8.5
  uuid: ^4.3.3
  pdf: ^3.10.8
  open_file: ^3.3.2
  universal_html: ^2.2.4
 # syncfusion_flutter_pdfviewer: ^24.2.8
 # webview_flutter: ^4.7.0
  # flutter_inappwebview: ^5.8.0
  flutter_pdfview: ^1.3.2
 
  printing: ^5.12.0
  fl_chart: ^0.67.0
  excel: ^4.0.2
  file_picker: 6.2.1
  collection: ^1.18.0
  #velocity_x: ^4.1.1
  #excel: ^4.0.2
  flutter_quill: ^9.3.21
  quill_html_editor: ^2.2.8
  quill_html_converter: ^9.3.21
  
  #quill_html_converter: ^9.3.21
  webview_flutter_web: ^0.2.3+2
  webview_flutter: ^4.8.0
  webview_flutter_platform_interface: ^2.10.0
  velocity_x:
    path: packages/velocity_x
  quill_delta: ^3.0.0-nullsafety.2
  #encrypt: ^5.0.3
  #archive: ^3.4.8
  js: ^0.7.1
   
     

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true

 
  assets:
   - assets/icons/
   - assets/images/
   - assets/Backgrounds/
   - assets/
   - assets/fonts/muli/
   - assets/fonts/roboto/
   - assets/fonts/openSans/
   - assets/fonts/lato/
   - assets/WebLocal/js/
   - assets/WebLocal/html/
   - assets/WebLocal/js/metroStyle.css
    
fonts:
  - family: Muli
    fonts:
      - asset: assets/fonts/muli/Muli.ttf
      - asset: assets/fonts/muli/Muli-Bold.ttf
        weight: 700
      - asset: assets/fonts/muli/Muli-Light.ttf
        weight: 300
  - family: OpenSans
    fonts:
      - asset: assets/fonts/openSans/OpenSans-Regular.ttf
      - asset: assets/fonts/openSans/OpenSans-Bold.ttf
      - asset: assets/fonts/openSans/OpenSans-Italic.ttf
      - asset: assets/fonts/openSans/OpenSans-BoldItalic.ttf  
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Regular.ttf
      - asset: assets/fonts/roboto/Roboto-Bold.ttf
      - asset: assets/fonts/roboto/Roboto-Italic.ttf
      - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf       
  - family: Lato
    fonts:
      - asset: assets/fonts/lato/Lato-Regular.ttf
      - asset: assets/fonts/lato/Lato-Bold.ttf
      - asset: assets/fonts/lato/Lato-Italic.ttf
      - asset: assets/fonts/lato/Lato-BoldItalic.ttf  